name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # 最新のUbuntuでワークフローを実行
    runs-on: ubuntu-latest

    steps:
      # ソースコードをGitからチェックアウト
      - uses: actions/checkout@v4
      # Gradleラッパースクリプトが正しいものか確認
      - uses: gradle/wrapper-validation-action@v1

      # dockerを立ち上げる
      - name: Up container
        run: docker compose up -d

      # Java 17 を使えるようにする
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Gradleビルドを実行
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
