name: Build

on:
  - push

jobs:
  build:
    # 最新のUbuntuでワークフローを実行
    runs-on: ubuntu-latest

    steps:
      # ソースコードをGitからチェックアウト
      - uses: actions/checkout@v4
      # Gradleラッパースクリプトが正しいものか確認
      - uses: gradle/wrapper-validation-action@v1

      - name: Up container
        run: docker compose up -d

      # Java 17 を使えるようにする
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          #          microsoft と　temurin　で何が違う？
          #          distribution: microsoft
          distribution: temurin
          java-version: 17

      - name: Store reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/test

      # Gradleビルドを実行
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

#      - name: Build with Gradle (without tests)
#        run: ./gradlew build -x test
#
#      - name: Run tests
#        run: ./gradlew test




#name: Java CI with Gradle
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#
#permissions:
#  contents: read
#  checks: write
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#        with:
#          arguments: build
